services:
  jenkins:
    build: .
    container_name: jenkins_ITS
    privileged: true
    user: root
    volumes:
      - jenkins_ITS:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - "8585:8080"
      - "50000:50000"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock

volumes:
  jenkins_ITS: