name: Linting

on:
  push:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13.2'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8
        run: flake8 --exclude=.venv .

      - name: Run pycodestyle
        run: pycodestyle --exclude=.venv .

      - name: Run pylint
        run: pylint --ignore=.venv **/*.py